### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by amardeepthadisetty** [kayusgold/laravel-cashfree-api#3]
How to use it, after installation? 
Can anybody guide me, after setting up the providor class??

**Comment by kayusgold** [comment]
Please follow the instructions in the readme and then check cash free doc

**Comment by kayusgold** [comment]
Cashfree payment gateway is divided into two: PaymentGateway and Marketplace. Please go through their documentation to understand how they work and differs. 

In this package, I also divided the package into two: PaymentGateway (src/PaymentGateway) and Marketplace (src/).

For example, using Cashfree for payment, requires creating a payment link and either displaying it to customer to fill their cards and pay or sending the link to customer (e.g email) and they open it, make payment and are redirected to the url you have specified while creating the payment link. To achieve this using this package, we will do:


``use LoveyCom\CashFree\PaymentGateway\Order;``
``$order_details = [``
  ``          'orderId' => '123',``
    ``        'orderAmount' => '1000',``
      ``      'orderCurrency' => 'USD',``
        ``    'customerName' => 'Test Customer',``
    ``        'customerPhone' => '',``
      ``      'customerEmail' => 'test@email.com',``
  ``          'returnUrl' => 'https://your_url_endpoint'``
    ``    ];``
      ``  $order = new Order();``
        ``$resp = $order->create($order_details);``
``
$resp is a json containing the this:

`` {status":"OK","paymentLink":"https:// payments-test.cashfree.com/orde/#D8LQswj8pOFuBnklt2GS"} ``

The other endpoints of cashfree api works in this way too. Just study the doc and look at the src folder of this package to see the function/method that performs the endpoint function.

If you need more assistance, let me know.

Happy coding.

**Comment by kayusgold** [comment]
> 
> 
> How to use it, after installation?
> Can anybody guide me, after setting up the providor class??

The package has just been updated (Typo Error Fix) and example added to the readme file.

Thanks.
