### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by ashishnishad** [kayusgold/laravel-cashfree-api#6]
if (PaymentGatewayBase::isProduction()) {
            $apiEndpoint = PaymentGatewayBase::geProdURL();
        } else {
            $apiEndpoint = PaymentGatewayBase::getTestURL();
        }
vendor/loveycom/cashfree/src/PaymentGateway/Order.php line 42 if block typo error , you missed 't' in geProdURL() function

**Comment by kayusgold** [comment]
Thanks for this. Typo fixed in the new release.
