### ISSUE TITLE
Trigger Payment Email

### ISSUE THREAD

**Issue by RohitM-IN** [kayusgold/laravel-cashfree-api#8]
in DOCS there is something called  Trigger Payment Email here https://dev.cashfree.com/payment-gateway-api#get-status
where you need to give merchant generated order id and an email will be sent of transaction idk the template but i didnt find this in readme 
```
  curl --request POST \
  --url https://test.cashfree.com/api/v1/order/email \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'appId=${APPLICATION_ID}&secretKey=${SECRET_KEY}&orderId=Testx1'
```

**Comment by kayusgold** [comment]
Well, I am sorry the package did not cover this endpoint, you can contribute this endpoint if you know how to, you can also extend the package in your code.

However, I will check this endpoint and see what I can do within short time. 

Thanks.
